new gui added for selecting games -credit to relacement
explosivegaming/factorio-olympics pull request #25
Opened 2020-08-20 16:19 UTC by tovernaar123

- the gui allows all players to pick a game from the list and join it 
- it list all the players that are particpating in the event 
-gui is mainly there to make it easier to join new servers
-credit to relacement for helping me make it

2020-08-21 18:43 UTC, Cooldude2606 requested changes
A few changes that I would like to be made, as well as a few suggestions to improve performance.

2020-08-21 18:43 UTC, Cooldude2606 commented on expcore/Mini_games.lua
> +        end
`gui_table.clear()` would have the same effect as this.

2020-08-21 18:43 UTC, Cooldude2606 commented on expcore/Mini_games.lua
> +            end
Is a loop required every time? Would it not be simpler to add one to the current count or just use `#participants`

2020-08-21 18:43 UTC, Cooldude2606 commented on expcore/Mini_games.lua
> +        player.print('You are now in the game server.')
Should be `You are now in a game server.` as there are multiple game servers.

2020-08-21 18:43 UTC, Cooldude2606 commented on expcore/Mini_games.lua
> +        end
See above comment for the loop on player join.

2020-08-21 18:43 UTC, Cooldude2606 commented on expcore/Mini_games.lua
>      end
Good bug fix but might be better to ignore `i` and use `Mini_games.remove_participant(participants[1])` as then remove participant doesnt need to do the search to find the player.

2020-08-21 18:43 UTC, Cooldude2606 commented on expcore/Mini_games.lua
> +            name = '\n[color=red]Factorio Olympics: '.."lobby"..'[/color]\n',
Just a suggestion to change this (as well as all other connect to server calls) to use `[font=heading-1]` and `[/font]` so that the title is bigger and easier to see.

2020-08-21 18:43 UTC, Cooldude2606 commented on expcore/Mini_games.lua
> +        name = '\n[color=red]Factorio Olympics: '..lobbyData.name..'[/color]\n',
See above comment for suggestion about using a different font.

2020-08-21 18:43 UTC, Cooldude2606 commented on expcore/Mini_games.lua
> +    }
Can be made into a single label with some left padding set on its style.

2020-08-21 18:43 UTC, Cooldude2606 commented on expcore/Mini_games.lua
> +	local scroll_table = Gui.scroll_table(container, 250, 1)
Uses a table with only 1 colum, this should be increased rather than using `start_flow` to contain the labels. (the flow would still be required for the button)

2020-08-21 18:43 UTC, Cooldude2606 commented on expcore/Mini_games.lua
> +        end
`gui_table.clear()` would have the same effect.

2020-08-21 18:43 UTC, Cooldude2606 commented on expcore/Mini_games.lua
> +    Mini_games.server_list_updated()
Does the whole list need to be redrawn when you change the players for one server? Would be better if only the label for that server was updated.

2020-08-21 18:46 UTC, tovernaar123 commented on expcore/Mini_games.lua
>      end
yeah that would work too

2020-08-21 18:48 UTC, tovernaar123 commented on expcore/Mini_games.lua
> +	local scroll_table = Gui.scroll_table(container, 250, 1)
this would be good if i dont want to clear the gui every so often to redraw it

2020-08-22 11:19 UTC, tovernaar123 commented on expcore/Mini_games.lua
> +    Mini_games.server_list_updated()
yes

2020-08-22 11:19 UTC, tovernaar123 commented on expcore/Mini_games.lua
> +    Mini_games.server_list_updated()
it does need to compelty redwarn as thats so much easier :P

2020-08-22 15:07 UTC, Cooldude2606 commented on expcore/Mini_games.lua
> +    Mini_games.server_list_updated()
So much easier than doing `label.caption = '1/ 4 PLayers'` ?

2020-08-22 15:08 UTC, Cooldude2606 commented on expcore/Mini_games.lua
> +	local scroll_table = Gui.scroll_table(container, 250, 1)
Why does the redraw frequency have relavents to this? Table and flows are style choises not really anything to do with preformance.

2020-08-22 17:08 UTC, Cooldude2606 requested changes
Only a few more changes to be made, although there is a desync risk with one of them.

2020-08-22 17:08 UTC, Cooldude2606 commented on expcore/Mini_games.lua
> +local amount_of_parts = 0
Must be a global otherwise there is risk of desync.

2020-08-22 17:08 UTC, Cooldude2606 commented on expcore/Mini_games.lua
> +        caption =  '        '..currentPlayer..' / '..maxPlayer..' Players',
Left padding was added, but the spaces are still included in the string. These spaces should be removed.

2020-08-22 17:08 UTC, Cooldude2606 commented on expcore/Mini_games.lua
> +	local scroll_table = Gui.scroll_table(container, 250, 1)
Table coloum count must be increased to 3 as there are now is now the start_flow, the game name, and player count label.

2020-08-22 17:08 UTC, Cooldude2606 commented on modules/gui/player-list.lua
> +            local scroll_table = section(container, name, 2).parent
This line should be reverted back to `local scroll_table = container[name]`

2020-08-22 20:13 UTC, Cooldude2606 requested changes
Still a few more changes needed, but most of it is done now.

2020-08-22 20:13 UTC, Cooldude2606 commented on expcore/Mini_games.lua
> +        if Roles.player_has_role(player, 'Participant') then
Could you move the `local participant` to under `local player` so that this call does not need to be repeated.

2020-08-22 20:13 UTC, Cooldude2606 commented on expcore/Mini_games.lua
> +    game.write_file('mini_games/player_count_changed', game.table_to_json(data), false, 0)
This code is repeated 4 times. I would suggest to move it into a functin such as `change_participants_online(delta)`

2020-08-22 20:13 UTC, Cooldude2606 commented on expcore/Mini_games.lua
> +Event.add(Roles.events.on_role_assigned, role_event_filter(part_role_added))
If the above suggestion is used then this will need to be chagned to:
```lua
Event.add(Roles.events.on_role_assigned, role_event_filter(function(player)
    check_participant_selector_join(player)
    change_participants_online(1)
end))

2020-08-22 20:13 UTC, Cooldude2606 commented on expcore/Mini_games.lua
> +Event.add(Roles.events.on_role_unassigned, role_event_filter(part_role_removed))
If the above suggestion is used then this will need to be chagned to:
```lua
Event.add(Roles.events.on_role_assigned, role_event_filter(function(player)
    check_participant_selector_leave(player)
    change_participants_online(-1)
end))

2020-08-22 20:13 UTC, Cooldude2606 commented on expcore/Mini_games.lua
> +            game.write_file('mini_games/player_count_changed', game.table_to_json(data), false, 0)
If the above suggestion is used then this will need to be chagned to:
`change_participants_online(1)`

2020-08-22 20:13 UTC, Cooldude2606 commented on expcore/Mini_games.lua
> +        game.write_file('mini_games/player_count_changed', game.table_to_json(data), false, 0)
If the above suggestion is used then this will need to be chagned to:
`change_participants_online(-1)`

2020-08-22 20:13 UTC, Cooldude2606 commented on expcore/Mini_games.lua
> +    Mini_games.server_list_updated()
You have added the code to update the effected server, but you still have the line which redraws the whole table, this should be removed.

2020-08-23 11:31 UTC, merged